#!/bin/bash
# scm Startup script
#
# chkconfig: - 85 15
# description: 
# processname: scm
# pidfile: /var/run/scm.pid

scmd=/usr/local/scm/scm
scm_pid=/var/run/scm.pid

RETVAL=0
prog="scm"

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

[ -x $scmd ] || exit 0


# Start scm daemons functions.
start() {
        if [ -e $scm_pid ];then
          echo "scm already running...."
          exit 1
        fi

	DAEMON_COREFILE_LIMIT="unlimited"
        echo -n $"Starting $prog: "
        daemon $scmd
        RETVAL=$?
        echo
        return $RETVAL
}


# Stop scm daemons functions.
stop() {
        echo -n $"Stopping $prog: "
        killproc $scmd -TERM
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f /var/run/scm.pid
}

# See how we were called.
case "$1" in
start)
        start
        ;;

stop)
        stop
        ;;

restart)
        stop
        start
        ;;

status)
        status $prog
        RETVAL=$?
        ;;
*)
        echo $"Usage: $prog {start|stop|restart|status|help}"
        exit 1
esac

exit $RETVAL

