/*================================================================
*   Created by LiXingang
*   Description: 
*
================================================================*/
#ifndef _BPF_OSHELPER_H
#define _BPF_OSHELPER_H
#ifdef __cplusplus
extern "C"
{
#endif

#if 0
typedef struct {
    long long err; 
    char *name;
    void * func;
}BPF_OSHELPER_S;

static BPF_OSHELPER_S g_bpf_os_helper[1024] = {
    {0},
    {.err=0, .name="bpf_map_lookup_elem"},
    {.err=-1, .name="bpf_map_update_elem"},
    {.err=-1, .name="bpf_map_delete_elem"},
    {.err=-1, .name="bpf_probe_read"},
    {.err=0, .name="bpf_ktime_get_ns"},
    {.err=-1, .name="bpf_trace_printk"},
    {.err=0, .name="bpf_user_rnd_u32"},
    {.err=0, .name="bpf_get_smp_processor_id"},
    {.err=-1, .name="bpf_skb_store_bytes"},
    {.err=-1, .name="bpf_l3_csum_replace"},
    {.err=-1, .name="bpf_l4_csum_replace"},
    {.err=-1, .name=NULL}, 
    {.err=-1, .name="bpf_clone_redirect"},
    {.err=0, .name="bpf_get_current_pid_tgid"},
    {.err=0, .name="bpf_get_current_uid_gid"},
    {.err=-1, .name="bpf_get_current_comm"},
    {.err=0, .name="bpf_get_cgroup_classid"},
    {.err=-1, .name="bpf_skb_vlan_push"},
    {.err=-1, .name="bpf_skb_vlan_pop"},
    {.err=-1, .name="bpf_skb_get_tunnel_key"},
    {.err=-1, .name="bpf_skb_set_tunnel_key"},
    {.err=-1, .name="bpf_perf_event_read"},
    {.err=0, .name="bpf_redirect"},
    {.err=0, .name="bpf_get_route_realm"},
    {.err=-1, .name="bpf_perf_event_output"},
    {.err=-1, .name="bpf_skb_load_bytes"},
    {.err=-1, .name="bpf_get_stackid"},
    {.err=-1, .name="bpf_csum_diff"},
    {.err=0, .name="bpf_skb_get_tunnel_opt"},
    {.err=-1, .name="bpf_skb_set_tunnel_opt"},
    {.err=-1, .name="bpf_skb_change_proto"},
    {.err=-1, .name="bpf_skb_change_type"},
    {.err=-1, .name="bpf_skb_under_cgroup"},
    {.err=0, .name="bpf_get_hash_recalc"},
    {.err=0, .name="bpf_get_current_task"},
    {.err=-1, .name="bpf_probe_write_user"},
    {.err=-1, .name="bpf_current_task_under_cgroup"},
    {.err=-1, .name="bpf_skb_change_tail"},
    {.err=-1, .name="bpf_skb_pull_data"},
    {.err=-1, .name="bpf_csum_update"},
    {.err=0, .name="bpf_set_hash_invalid"},
    {.err=0, .name="bpf_get_numa_node_id"},
    {.err=-1, .name="bpf_skb_change_head"},
    {.err=-1, .name="bpf_xdp_adjust_head"},
    {.err=-1, .name="bpf_probe_read_str"},
    {.err=0, .name="bpf_get_socket_cookie"},
    {.err=65534, .name="bpf_get_socket_uid"},
    {.err=0, .name="bpf_set_hash"},
    {.err=-1, .name="bpf_setsockopt"},
    {.err=-1, .name="bpf_skb_adjust_room"},
    {.err=0, .name="bpf_xdp_redirect_map"},
    {.err=0, .name="bpf_sk_redirect_map"},
    {.err=-1, .name="bpf_sock_map_update"},
    {.err=-1, .name="bpf_xdp_adjust_meta"},
    {.err=-1, .name="bpf_perf_event_read_value"},
    {.err=-1, .name="bpf_perf_prog_read_value"},
    {.err=-1, .name="bpf_getsockopt"},
    {.err=0, .name="bpf_override_return"},
    {.err=-1, .name="bpf_sock_ops_cb_flags_set"},
    {.err=0, .name="bpf_msg_redirect_map"},
    {.err=0, .name="bpf_msg_apply_bytes"},
    {.err=0, .name="bpf_msg_cork_bytes"},
    {.err=-1, .name="bpf_msg_pull_data"},
    {.err=-1, .name="bpf_bind"},
    {.err=-1, .name="bpf_xdp_adjust_tail"},
    {.err=-1, .name="bpf_skb_get_xfrm_state"},
    {.err=-1, .name="bpf_get_stack"},
    {.err=-1, .name="bpf_skb_load_bytes_relative"},
    {.err=-1, .name=NULL}, 
    {.err=-1, .name="bpf_sock_hash_update"},
    {.err=0, .name="bpf_msg_redirect_hash"},
    {.err=0, .name="bpf_sk_redirect_hash"},
    {.err=-1, .name="bpf_lwt_push_encap"},
    {.err=-1, .name="bpf_lwt_seg6_store_bytes"},
    {.err=-1, .name="bpf_lwt_seg6_adjust_srh"},
    {.err=-1, .name="bpf_lwt_seg6_action"},
    {.err=0, .name="bpf_rc_repeat"},
    {.err=0, .name="bpf_rc_keydown"},
    {.err=0, .name="bpf_skb_cgroup_id"},
    {.err=0, .name="bpf_get_current_cgroup_id"},
    {.err=0, .name="bpf_get_local_storage"},
    {.err=-1, .name="sk_select_reuseport"},
    {.err=0, .name="bpf_skb_ancestor_cgroup_id"},
    {.err=0, .name="bpf_sk_lookup_tcp"},
    {.err=0, .name="bpf_sk_lookup_udp"},
    {.err=-1, .name="bpf_sk_release"},
    {.err=-1, .name="bpf_map_push_elem"},
    {.err=-1, .name="bpf_map_pop_elem"},
    {.err=-1, .name="bpf_map_peek_elem"},
    {.err=-1, .name="bpf_msg_push_data"},
    {.err=-1, .name="bpf_msg_pop_data"},
    {.err=0, .name="bpf_rc_pointer_rel"},
    {.err=0, .name="bpf_spin_lock"},
    {.err=0, .name="bpf_spin_unlock"},
    {.err=0, .name="bpf_sk_fullsock"},
    {.err=0, .name="bpf_tcp_sock"},
    {.err=0, .name="bpf_skb_ecn_set_ce"},
    {.err=0, .name="bpf_get_listener_sock"},
    {.err=0, .name="bpf_skc_lookup_tcp"},
    {.err=-1, .name="bpf_tcp_check_syncookie"},
    {.err=-EINVAL, .name="bpf_sysctl_get_name"},
    {.err=-EINVAL, .name="bpf_sysctl_get_current_value"},
    {.err=-EINVAL, .name="bpf_sysctl_get_new_value"},
    {.err=-EINVAL, .name="bpf_sysctl_set_new_value"},
    {.err=-EINVAL, .name="bpf_strtol"},
    {.err=-EINVAL, .name="bpf_strtoul"},
    {.err=0, .name="bpf_sk_storage_get"},
    {.err=-1, .name="bpf_sk_storage_delete"},
    {.err=-EINVAL, .name="bpf_send_signal"},
    {.err=-EINVAL, .name="bpf_tcp_gen_syncookie"},
    {.err=-1, .name="bpf_skb_output"},
    {.err=-1, .name="bpf_probe_read_user"},
    {.err=-1, .name="bpf_probe_read_kernel"},
    {.err=-1, .name="bpf_probe_read_user_str"},
    {.err=-1, .name="bpf_probe_read_kernel_str"},
    {.err=-1, .name="bpf_tcp_send_ack"},
    {.err=-1, .name="bpf_send_signal_thread"},
    {.err=0, .name="bpf_jiffies64"},
    {.err=-1, .name="bpf_read_branch_records"},
    {.err=-1, .name="bpf_get_ns_current_pid_tgid"},
    {.err=-1, .name="bpf_xdp_output"},
    {.err=-1, .name="bpf_get_netns_cookie"},
    {.err=0, .name="bpf_get_current_ancestor_cgroup_id"},
    {.err=-1, .name="bpf_sk_assign"},
    {.err=0, .name="bpf_ktime_get_boot_ns"},
    {.err=-1, .name="bpf_seq_printf"},
    {.err=-1, .name="bpf_seq_write"},
    {.err=0, .name="bpf_sk_cgroup_id"},
    {.err=0, .name="bpf_sk_ancestor_cgroup_id"},
    {.err=-1, .name="bpf_ringbuf_output"},
    {.err=0, .name="bpf_ringbuf_reserve"},
    {.err=0, .name="bpf_ringbuf_submit"},
    {.err=0, .name="bpf_ringbuf_discard"},
    {.err=0, .name="bpf_ringbuf_query"},
    {.err=-1, .name="bpf_csum_level"},
    {.err=0, .name="bpf_skc_to_tcp6_sock"},
    {.err=0, .name="bpf_skc_to_tcp_sock"},
    {.err=0, .name="bpf_skc_to_tcp_timewait_sock"},
    {.err=0, .name="bpf_skc_to_tcp_request_sock"},
    {.err=0, .name="bpf_skc_to_udp6_sock"},
    {.err=-1, .name="bpf_get_task_stack"},
};
#endif

#ifdef __cplusplus
}
#endif
#endif 
